### ISSUE TITLE
Asset folder is missing

### ISSUE THREAD

**Issue by ejaazrkhan** [amansuryawanshi/Gym-Website-and-Management-System#1]
All the images and js files are inside asset folder and asset folder is missing
![image](https://user-images.githubusercontent.com/51430814/218260377-971f0837-ff60-4009-bfd5-cab5727397b0.png)
![image](https://user-images.githubusercontent.com/51430814/218260393-483efa9d-3ad2-402d-aec3-164cdaa4fa33.png)

**Comment by amansuryawanshi** [comment]
https://drive.google.com/folderview?id=1GLcOT-txKMbFFGl02-uCZZokK0sg42TV

You can use this I have uploaded the details here I think it should have
everything

**Comment by ejaazrkhan** [comment]
Thankyou @amansuryawanshi
